name: Code quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v7

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build packages
        run: vp build

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v7

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run tests
        run: vp test

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v7

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run check
        run: vp check
